name: Run Regression Tests on Main Branch

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-regression-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "11"

      - name: Install Maven
        run: sudo apt-get install -y maven

      - name: Run regression tests
        run: mvn clean test -Dtest.groups=regression -Dheadless=true
