name: Run Regression Tests

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  run-regression-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "11"

      - name: Install Maven
        run: sudo apt-get install -y maven

      - name: Run regression tests in headless mode
        run: mvn clean test -Dtest.groups=regression -Dheadless=true
